### ISSUE TITLE
not getting the correct uri

### ISSUE THREAD

**Issue by calixto111** [epsil/spotify-js#1]
HI, I think there is a problem here
when you input 
Michael Jackson - off the wall 
you get spotify:track:46eu3SBuFCXWsPT39Yg3tJ
which is a different song , I think billie Jean
it is supposed to get this one 
spotify:track:3zYpRGnnoegSpt3SguSo3W
can you please check on the this and let me know
thanks

**Comment by epsil** [comment]
Should be fixed.
