### ISSUE TITLE
WORKING NOW , CAN YOU DO ALBUMS ALSO?

### ISSUE THREAD

**Issue by calixto111** [epsil/spotify-js#2]
k

**Comment by epsil** [comment]
It's doable, but a little tricky the way the code is structured now.

May I ask what you need the album URI for? I am unsure what your use case is.

**Comment by calixto111** [comment]
I need to save the album uri in a data base that I have

**Comment by calixto111** [comment]
is there any way I can edit the code to have this result?
thanks

**Comment by epsil** [comment]
A database, you say? Please tell me more! I'm curious. :)

I have added (experimentially) an `#albumid` directive. So

    #albumid Off the Wall - Michael Jackson

will give you the album URI for the *Off the Wall* album of Michael Jackson, while

    #album Off the Wall - Michael Jackson

will give you the track URIs for all the tracks on the *Off the Wall* album.

**Comment by calixto111** [comment]
very good , I use it for spotify-ripper
https://github.com/hbashton/spotify-ripper
